### ISSUE TITLE
NGXTable: Add ARIA compliance to NgxTable

### ISSUE THREAD

**Issue by IbenTesara** [studiohyperdrive/ngx-tools#220]
The `ngx-table` allows for a detail row to be implemented. Because of that, from the moment one is provided, the table de-facto becomes a `treegrid.

Because of that, we need to take all the rules of a `treegrid` into account to be WCAG/ARIA compliant, but only when a detail-row is present.
https://www.w3.org/WAI/ARIA/apg/patterns/treegrid/

**Comment by WHeirstrate** [comment]
Good luck 💪
