### ISSUE TITLE
[Global]: Move "studiohyperdrive/pagination" to "hypedrive-open-source"

### ISSUE THREAD

**Issue by IbenTesara** [studiohyperdrive/ngx-tools#287]
Move the current "studiohyperdrive/pagination" to the "hypedrive-open-source" repository

**Comment by bertyhell** [comment]
This won't be neccessary anymore since the HAL tools do the same thing
Closing this issue in favor of [289](https://github.com/studiohyperdrive/ngx-tools/issues/289)
